// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="pixel_unpack_pixel_unpack,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=7.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=1.978000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=330,HLS_SYN_LUT=806,HLS_VERSION=2022_1}" *)

module pixel_unpack (
        ap_clk,
        ap_rst_n,
        stream_in_32_TDATA,
        stream_in_32_TVALID,
        stream_in_32_TREADY,
        stream_in_32_TKEEP,
        stream_in_32_TSTRB,
        stream_in_32_TUSER,
        stream_in_32_TLAST,
        stream_out_24_TDATA,
        stream_out_24_TVALID,
        stream_out_24_TREADY,
        stream_out_24_TKEEP,
        stream_out_24_TSTRB,
        stream_out_24_TUSER,
        stream_out_24_TLAST,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [31:0] stream_in_32_TDATA;
input   stream_in_32_TVALID;
output   stream_in_32_TREADY;
input  [3:0] stream_in_32_TKEEP;
input  [3:0] stream_in_32_TSTRB;
input  [0:0] stream_in_32_TUSER;
input  [0:0] stream_in_32_TLAST;
output  [23:0] stream_out_24_TDATA;
output   stream_out_24_TVALID;
input   stream_out_24_TREADY;
output  [2:0] stream_out_24_TKEEP;
output  [2:0] stream_out_24_TSTRB;
output  [0:0] stream_out_24_TUSER;
output  [0:0] stream_out_24_TLAST;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;

 reg    ap_rst_n_inv;
wire   [31:0] mode;
reg   [31:0] mode_0_data_reg;
reg    mode_0_vld_reg;
reg    mode_0_ack_out;
wire   [31:0] grp_read_fu_76_p2;
reg   [31:0] mode_read_reg_202;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state2;
wire    grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_82_ap_start;
wire    grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_82_ap_done;
wire    grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_82_ap_idle;
wire    grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_82_ap_ready;
wire    grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_82_stream_out_24_TREADY;
wire    grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_82_stream_in_32_TREADY;
wire   [23:0] grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_82_stream_out_24_TDATA;
wire    grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_82_stream_out_24_TVALID;
wire   [2:0] grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_82_stream_out_24_TKEEP;
wire   [2:0] grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_82_stream_out_24_TSTRB;
wire   [0:0] grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_82_stream_out_24_TUSER;
wire   [0:0] grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_82_stream_out_24_TLAST;
wire    grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_106_ap_start;
wire    grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_106_ap_done;
wire    grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_106_ap_idle;
wire    grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_106_ap_ready;
wire    grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_106_stream_out_24_TREADY;
wire    grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_106_stream_in_32_TREADY;
wire   [23:0] grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_106_stream_out_24_TDATA;
wire    grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_106_stream_out_24_TVALID;
wire   [2:0] grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_106_stream_out_24_TKEEP;
wire   [2:0] grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_106_stream_out_24_TSTRB;
wire   [0:0] grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_106_stream_out_24_TUSER;
wire   [0:0] grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_106_stream_out_24_TLAST;
wire    grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_130_ap_start;
wire    grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_130_ap_done;
wire    grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_130_ap_idle;
wire    grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_130_ap_ready;
wire    grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_130_stream_out_24_TREADY;
wire    grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_130_stream_in_32_TREADY;
wire   [23:0] grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_130_stream_out_24_TDATA;
wire    grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_130_stream_out_24_TVALID;
wire   [2:0] grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_130_stream_out_24_TKEEP;
wire   [2:0] grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_130_stream_out_24_TSTRB;
wire   [0:0] grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_130_stream_out_24_TUSER;
wire   [0:0] grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_130_stream_out_24_TLAST;
wire    grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_154_ap_start;
wire    grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_154_ap_done;
wire    grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_154_ap_idle;
wire    grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_154_ap_ready;
wire    grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_154_stream_out_24_TREADY;
wire    grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_154_stream_in_32_TREADY;
wire   [23:0] grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_154_stream_out_24_TDATA;
wire    grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_154_stream_out_24_TVALID;
wire   [2:0] grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_154_stream_out_24_TKEEP;
wire   [2:0] grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_154_stream_out_24_TSTRB;
wire   [0:0] grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_154_stream_out_24_TUSER;
wire   [0:0] grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_154_stream_out_24_TLAST;
wire    grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_178_ap_start;
wire    grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_178_ap_done;
wire    grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_178_ap_idle;
wire    grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_178_ap_ready;
wire    grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_178_stream_out_24_TREADY;
wire    grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_178_stream_in_32_TREADY;
wire   [23:0] grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_178_stream_out_24_TDATA;
wire    grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_178_stream_out_24_TVALID;
wire   [2:0] grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_178_stream_out_24_TKEEP;
wire   [2:0] grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_178_stream_out_24_TSTRB;
wire   [0:0] grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_178_stream_out_24_TUSER;
wire   [0:0] grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_178_stream_out_24_TLAST;
reg    grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_82_ap_start_reg;
wire    ap_CS_fsm_state3;
reg    grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_106_ap_start_reg;
reg    grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_130_ap_start_reg;
reg    grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_154_ap_start_reg;
reg    grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_178_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    regslice_both_stream_out_24_V_data_V_U_apdone_blk;
reg   [3:0] ap_NS_fsm;
wire    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_block_state3_on_subcall_done;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    regslice_both_stream_in_32_V_data_V_U_apdone_blk;
wire   [31:0] stream_in_32_TDATA_int_regslice;
wire    stream_in_32_TVALID_int_regslice;
reg    stream_in_32_TREADY_int_regslice;
wire    regslice_both_stream_in_32_V_data_V_U_ack_in;
wire    regslice_both_stream_in_32_V_keep_V_U_apdone_blk;
wire   [3:0] stream_in_32_TKEEP_int_regslice;
wire    regslice_both_stream_in_32_V_keep_V_U_vld_out;
wire    regslice_both_stream_in_32_V_keep_V_U_ack_in;
wire    regslice_both_stream_in_32_V_strb_V_U_apdone_blk;
wire   [3:0] stream_in_32_TSTRB_int_regslice;
wire    regslice_both_stream_in_32_V_strb_V_U_vld_out;
wire    regslice_both_stream_in_32_V_strb_V_U_ack_in;
wire    regslice_both_stream_in_32_V_user_V_U_apdone_blk;
wire   [0:0] stream_in_32_TUSER_int_regslice;
wire    regslice_both_stream_in_32_V_user_V_U_vld_out;
wire    regslice_both_stream_in_32_V_user_V_U_ack_in;
wire    regslice_both_stream_in_32_V_last_V_U_apdone_blk;
wire   [0:0] stream_in_32_TLAST_int_regslice;
wire    regslice_both_stream_in_32_V_last_V_U_vld_out;
wire    regslice_both_stream_in_32_V_last_V_U_ack_in;
reg   [23:0] stream_out_24_TDATA_int_regslice;
reg    stream_out_24_TVALID_int_regslice;
wire    stream_out_24_TREADY_int_regslice;
wire    regslice_both_stream_out_24_V_data_V_U_vld_out;
wire    regslice_both_stream_out_24_V_keep_V_U_apdone_blk;
reg   [2:0] stream_out_24_TKEEP_int_regslice;
wire    regslice_both_stream_out_24_V_keep_V_U_ack_in_dummy;
wire    regslice_both_stream_out_24_V_keep_V_U_vld_out;
wire    regslice_both_stream_out_24_V_strb_V_U_apdone_blk;
reg   [2:0] stream_out_24_TSTRB_int_regslice;
wire    regslice_both_stream_out_24_V_strb_V_U_ack_in_dummy;
wire    regslice_both_stream_out_24_V_strb_V_U_vld_out;
wire    regslice_both_stream_out_24_V_user_V_U_apdone_blk;
reg   [0:0] stream_out_24_TUSER_int_regslice;
wire    regslice_both_stream_out_24_V_user_V_U_ack_in_dummy;
wire    regslice_both_stream_out_24_V_user_V_U_vld_out;
wire    regslice_both_stream_out_24_V_last_V_U_apdone_blk;
reg   [0:0] stream_out_24_TLAST_int_regslice;
wire    regslice_both_stream_out_24_V_last_V_U_ack_in_dummy;
wire    regslice_both_stream_out_24_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 mode_0_data_reg = 32'd0;
#0 mode_0_vld_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_82_ap_start_reg = 1'b0;
#0 grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_106_ap_start_reg = 1'b0;
#0 grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_130_ap_start_reg = 1'b0;
#0 grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_154_ap_start_reg = 1'b0;
#0 grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_178_ap_start_reg = 1'b0;
end

pixel_unpack_pixel_unpack_Pipeline_VITIS_LOOP_85_9 grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_82(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_82_ap_start),
    .ap_done(grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_82_ap_done),
    .ap_idle(grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_82_ap_idle),
    .ap_ready(grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_82_ap_ready),
    .stream_out_24_TREADY(grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_82_stream_out_24_TREADY),
    .stream_in_32_TDATA(stream_in_32_TDATA_int_regslice),
    .stream_in_32_TVALID(stream_in_32_TVALID_int_regslice),
    .stream_in_32_TREADY(grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_82_stream_in_32_TREADY),
    .stream_in_32_TKEEP(stream_in_32_TKEEP_int_regslice),
    .stream_in_32_TSTRB(stream_in_32_TSTRB_int_regslice),
    .stream_in_32_TUSER(stream_in_32_TUSER_int_regslice),
    .stream_in_32_TLAST(stream_in_32_TLAST_int_regslice),
    .stream_out_24_TDATA(grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_82_stream_out_24_TDATA),
    .stream_out_24_TVALID(grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_82_stream_out_24_TVALID),
    .stream_out_24_TKEEP(grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_82_stream_out_24_TKEEP),
    .stream_out_24_TSTRB(grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_82_stream_out_24_TSTRB),
    .stream_out_24_TUSER(grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_82_stream_out_24_TUSER),
    .stream_out_24_TLAST(grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_82_stream_out_24_TLAST)
);

pixel_unpack_pixel_unpack_Pipeline_VITIS_LOOP_68_7 grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_106(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_106_ap_start),
    .ap_done(grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_106_ap_done),
    .ap_idle(grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_106_ap_idle),
    .ap_ready(grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_106_ap_ready),
    .stream_out_24_TREADY(grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_106_stream_out_24_TREADY),
    .stream_in_32_TDATA(stream_in_32_TDATA_int_regslice),
    .stream_in_32_TVALID(stream_in_32_TVALID_int_regslice),
    .stream_in_32_TREADY(grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_106_stream_in_32_TREADY),
    .stream_in_32_TKEEP(stream_in_32_TKEEP_int_regslice),
    .stream_in_32_TSTRB(stream_in_32_TSTRB_int_regslice),
    .stream_in_32_TUSER(stream_in_32_TUSER_int_regslice),
    .stream_in_32_TLAST(stream_in_32_TLAST_int_regslice),
    .stream_out_24_TDATA(grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_106_stream_out_24_TDATA),
    .stream_out_24_TVALID(grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_106_stream_out_24_TVALID),
    .stream_out_24_TKEEP(grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_106_stream_out_24_TKEEP),
    .stream_out_24_TSTRB(grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_106_stream_out_24_TSTRB),
    .stream_out_24_TUSER(grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_106_stream_out_24_TUSER),
    .stream_out_24_TLAST(grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_106_stream_out_24_TLAST)
);

pixel_unpack_pixel_unpack_Pipeline_VITIS_LOOP_51_5 grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_130(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_130_ap_start),
    .ap_done(grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_130_ap_done),
    .ap_idle(grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_130_ap_idle),
    .ap_ready(grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_130_ap_ready),
    .stream_out_24_TREADY(grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_130_stream_out_24_TREADY),
    .stream_in_32_TDATA(stream_in_32_TDATA_int_regslice),
    .stream_in_32_TVALID(stream_in_32_TVALID_int_regslice),
    .stream_in_32_TREADY(grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_130_stream_in_32_TREADY),
    .stream_in_32_TKEEP(stream_in_32_TKEEP_int_regslice),
    .stream_in_32_TSTRB(stream_in_32_TSTRB_int_regslice),
    .stream_in_32_TUSER(stream_in_32_TUSER_int_regslice),
    .stream_in_32_TLAST(stream_in_32_TLAST_int_regslice),
    .stream_out_24_TDATA(grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_130_stream_out_24_TDATA),
    .stream_out_24_TVALID(grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_130_stream_out_24_TVALID),
    .stream_out_24_TKEEP(grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_130_stream_out_24_TKEEP),
    .stream_out_24_TSTRB(grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_130_stream_out_24_TSTRB),
    .stream_out_24_TUSER(grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_130_stream_out_24_TUSER),
    .stream_out_24_TLAST(grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_130_stream_out_24_TLAST)
);

pixel_unpack_pixel_unpack_Pipeline_VITIS_LOOP_40_4 grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_154(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_154_ap_start),
    .ap_done(grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_154_ap_done),
    .ap_idle(grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_154_ap_idle),
    .ap_ready(grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_154_ap_ready),
    .stream_in_32_TVALID(stream_in_32_TVALID_int_regslice),
    .stream_out_24_TREADY(grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_154_stream_out_24_TREADY),
    .stream_in_32_TDATA(stream_in_32_TDATA_int_regslice),
    .stream_in_32_TREADY(grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_154_stream_in_32_TREADY),
    .stream_in_32_TKEEP(stream_in_32_TKEEP_int_regslice),
    .stream_in_32_TSTRB(stream_in_32_TSTRB_int_regslice),
    .stream_in_32_TUSER(stream_in_32_TUSER_int_regslice),
    .stream_in_32_TLAST(stream_in_32_TLAST_int_regslice),
    .stream_out_24_TDATA(grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_154_stream_out_24_TDATA),
    .stream_out_24_TVALID(grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_154_stream_out_24_TVALID),
    .stream_out_24_TKEEP(grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_154_stream_out_24_TKEEP),
    .stream_out_24_TSTRB(grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_154_stream_out_24_TSTRB),
    .stream_out_24_TUSER(grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_154_stream_out_24_TUSER),
    .stream_out_24_TLAST(grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_154_stream_out_24_TLAST)
);

pixel_unpack_pixel_unpack_Pipeline_VITIS_LOOP_19_1 grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_178(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_178_ap_start),
    .ap_done(grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_178_ap_done),
    .ap_idle(grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_178_ap_idle),
    .ap_ready(grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_178_ap_ready),
    .stream_out_24_TREADY(grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_178_stream_out_24_TREADY),
    .stream_in_32_TDATA(stream_in_32_TDATA_int_regslice),
    .stream_in_32_TVALID(stream_in_32_TVALID_int_regslice),
    .stream_in_32_TREADY(grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_178_stream_in_32_TREADY),
    .stream_in_32_TKEEP(stream_in_32_TKEEP_int_regslice),
    .stream_in_32_TSTRB(stream_in_32_TSTRB_int_regslice),
    .stream_in_32_TUSER(stream_in_32_TUSER_int_regslice),
    .stream_in_32_TLAST(stream_in_32_TLAST_int_regslice),
    .stream_out_24_TDATA(grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_178_stream_out_24_TDATA),
    .stream_out_24_TVALID(grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_178_stream_out_24_TVALID),
    .stream_out_24_TKEEP(grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_178_stream_out_24_TKEEP),
    .stream_out_24_TSTRB(grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_178_stream_out_24_TSTRB),
    .stream_out_24_TUSER(grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_178_stream_out_24_TUSER),
    .stream_out_24_TLAST(grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_178_stream_out_24_TLAST)
);

pixel_unpack_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .mode(mode)
);

pixel_unpack_regslice_both #(
    .DataWidth( 32 ))
regslice_both_stream_in_32_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_32_TDATA),
    .vld_in(stream_in_32_TVALID),
    .ack_in(regslice_both_stream_in_32_V_data_V_U_ack_in),
    .data_out(stream_in_32_TDATA_int_regslice),
    .vld_out(stream_in_32_TVALID_int_regslice),
    .ack_out(stream_in_32_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_32_V_data_V_U_apdone_blk)
);

pixel_unpack_regslice_both #(
    .DataWidth( 4 ))
regslice_both_stream_in_32_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_32_TKEEP),
    .vld_in(stream_in_32_TVALID),
    .ack_in(regslice_both_stream_in_32_V_keep_V_U_ack_in),
    .data_out(stream_in_32_TKEEP_int_regslice),
    .vld_out(regslice_both_stream_in_32_V_keep_V_U_vld_out),
    .ack_out(stream_in_32_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_32_V_keep_V_U_apdone_blk)
);

pixel_unpack_regslice_both #(
    .DataWidth( 4 ))
regslice_both_stream_in_32_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_32_TSTRB),
    .vld_in(stream_in_32_TVALID),
    .ack_in(regslice_both_stream_in_32_V_strb_V_U_ack_in),
    .data_out(stream_in_32_TSTRB_int_regslice),
    .vld_out(regslice_both_stream_in_32_V_strb_V_U_vld_out),
    .ack_out(stream_in_32_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_32_V_strb_V_U_apdone_blk)
);

pixel_unpack_regslice_both #(
    .DataWidth( 1 ))
regslice_both_stream_in_32_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_32_TUSER),
    .vld_in(stream_in_32_TVALID),
    .ack_in(regslice_both_stream_in_32_V_user_V_U_ack_in),
    .data_out(stream_in_32_TUSER_int_regslice),
    .vld_out(regslice_both_stream_in_32_V_user_V_U_vld_out),
    .ack_out(stream_in_32_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_32_V_user_V_U_apdone_blk)
);

pixel_unpack_regslice_both #(
    .DataWidth( 1 ))
regslice_both_stream_in_32_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_32_TLAST),
    .vld_in(stream_in_32_TVALID),
    .ack_in(regslice_both_stream_in_32_V_last_V_U_ack_in),
    .data_out(stream_in_32_TLAST_int_regslice),
    .vld_out(regslice_both_stream_in_32_V_last_V_U_vld_out),
    .ack_out(stream_in_32_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_32_V_last_V_U_apdone_blk)
);

pixel_unpack_regslice_both #(
    .DataWidth( 24 ))
regslice_both_stream_out_24_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_out_24_TDATA_int_regslice),
    .vld_in(stream_out_24_TVALID_int_regslice),
    .ack_in(stream_out_24_TREADY_int_regslice),
    .data_out(stream_out_24_TDATA),
    .vld_out(regslice_both_stream_out_24_V_data_V_U_vld_out),
    .ack_out(stream_out_24_TREADY),
    .apdone_blk(regslice_both_stream_out_24_V_data_V_U_apdone_blk)
);

pixel_unpack_regslice_both #(
    .DataWidth( 3 ))
regslice_both_stream_out_24_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_out_24_TKEEP_int_regslice),
    .vld_in(stream_out_24_TVALID_int_regslice),
    .ack_in(regslice_both_stream_out_24_V_keep_V_U_ack_in_dummy),
    .data_out(stream_out_24_TKEEP),
    .vld_out(regslice_both_stream_out_24_V_keep_V_U_vld_out),
    .ack_out(stream_out_24_TREADY),
    .apdone_blk(regslice_both_stream_out_24_V_keep_V_U_apdone_blk)
);

pixel_unpack_regslice_both #(
    .DataWidth( 3 ))
regslice_both_stream_out_24_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_out_24_TSTRB_int_regslice),
    .vld_in(stream_out_24_TVALID_int_regslice),
    .ack_in(regslice_both_stream_out_24_V_strb_V_U_ack_in_dummy),
    .data_out(stream_out_24_TSTRB),
    .vld_out(regslice_both_stream_out_24_V_strb_V_U_vld_out),
    .ack_out(stream_out_24_TREADY),
    .apdone_blk(regslice_both_stream_out_24_V_strb_V_U_apdone_blk)
);

pixel_unpack_regslice_both #(
    .DataWidth( 1 ))
regslice_both_stream_out_24_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_out_24_TUSER_int_regslice),
    .vld_in(stream_out_24_TVALID_int_regslice),
    .ack_in(regslice_both_stream_out_24_V_user_V_U_ack_in_dummy),
    .data_out(stream_out_24_TUSER),
    .vld_out(regslice_both_stream_out_24_V_user_V_U_vld_out),
    .ack_out(stream_out_24_TREADY),
    .apdone_blk(regslice_both_stream_out_24_V_user_V_U_apdone_blk)
);

pixel_unpack_regslice_both #(
    .DataWidth( 1 ))
regslice_both_stream_out_24_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_out_24_TLAST_int_regslice),
    .vld_in(stream_out_24_TVALID_int_regslice),
    .ack_in(regslice_both_stream_out_24_V_last_V_U_ack_in_dummy),
    .data_out(stream_out_24_TLAST),
    .vld_out(regslice_both_stream_out_24_V_last_V_U_vld_out),
    .ack_out(stream_out_24_TREADY),
    .apdone_blk(regslice_both_stream_out_24_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_178_ap_start_reg <= 1'b0;
    end else begin
        if (((grp_read_fu_76_p2 == 32'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_178_ap_start_reg <= 1'b1;
        end else if ((grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_178_ap_ready == 1'b1)) begin
            grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_178_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_154_ap_start_reg <= 1'b0;
    end else begin
        if (((grp_read_fu_76_p2 == 32'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_154_ap_start_reg <= 1'b1;
        end else if ((grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_154_ap_ready == 1'b1)) begin
            grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_154_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_130_ap_start_reg <= 1'b0;
    end else begin
        if (((grp_read_fu_76_p2 == 32'd2) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_130_ap_start_reg <= 1'b1;
        end else if ((grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_130_ap_ready == 1'b1)) begin
            grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_130_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_106_ap_start_reg <= 1'b0;
    end else begin
        if (((grp_read_fu_76_p2 == 32'd3) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_106_ap_start_reg <= 1'b1;
        end else if ((grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_106_ap_ready == 1'b1)) begin
            grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_106_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_82_ap_start_reg <= 1'b0;
    end else begin
        if (((grp_read_fu_76_p2 == 32'd4) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_82_ap_start_reg <= 1'b1;
        end else if ((grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_82_ap_ready == 1'b1)) begin
            grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_82_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((mode_0_ack_out == 1'b1) & (1'b1 == 1'b1) & (mode_0_vld_reg == 1'b1)) | ((1'b1 == 1'b1) & (mode_0_vld_reg == 1'b0)))) begin
        mode_0_data_reg <= mode;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        mode_read_reg_202 <= mode_0_data_reg;
    end
end

assign ap_ST_fsm_state1_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state3_on_subcall_done)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_stream_out_24_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((regslice_both_stream_out_24_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state4)))) begin
        mode_0_ack_out = 1'b1;
    end else begin
        mode_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((mode_read_reg_202 == 32'd0)) begin
            stream_in_32_TREADY_int_regslice = grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_178_stream_in_32_TREADY;
        end else if ((mode_read_reg_202 == 32'd1)) begin
            stream_in_32_TREADY_int_regslice = grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_154_stream_in_32_TREADY;
        end else if ((mode_read_reg_202 == 32'd2)) begin
            stream_in_32_TREADY_int_regslice = grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_130_stream_in_32_TREADY;
        end else if ((mode_read_reg_202 == 32'd3)) begin
            stream_in_32_TREADY_int_regslice = grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_106_stream_in_32_TREADY;
        end else if ((mode_read_reg_202 == 32'd4)) begin
            stream_in_32_TREADY_int_regslice = grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_82_stream_in_32_TREADY;
        end else begin
            stream_in_32_TREADY_int_regslice = 1'b0;
        end
    end else begin
        stream_in_32_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if (((mode_read_reg_202 == 32'd0) & (grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_178_stream_out_24_TVALID == 1'b1))) begin
            stream_out_24_TDATA_int_regslice = grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_178_stream_out_24_TDATA;
        end else if (((mode_read_reg_202 == 32'd1) & (grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_154_stream_out_24_TVALID == 1'b1))) begin
            stream_out_24_TDATA_int_regslice = grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_154_stream_out_24_TDATA;
        end else if (((mode_read_reg_202 == 32'd2) & (grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_130_stream_out_24_TVALID == 1'b1))) begin
            stream_out_24_TDATA_int_regslice = grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_130_stream_out_24_TDATA;
        end else if (((grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_106_stream_out_24_TVALID == 1'b1) & (mode_read_reg_202 == 32'd3))) begin
            stream_out_24_TDATA_int_regslice = grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_106_stream_out_24_TDATA;
        end else if (((grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_82_stream_out_24_TVALID == 1'b1) & (mode_read_reg_202 == 32'd4))) begin
            stream_out_24_TDATA_int_regslice = grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_82_stream_out_24_TDATA;
        end else begin
            stream_out_24_TDATA_int_regslice = 'bx;
        end
    end else begin
        stream_out_24_TDATA_int_regslice = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if (((mode_read_reg_202 == 32'd0) & (grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_178_stream_out_24_TVALID == 1'b1))) begin
            stream_out_24_TKEEP_int_regslice = grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_178_stream_out_24_TKEEP;
        end else if (((mode_read_reg_202 == 32'd1) & (grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_154_stream_out_24_TVALID == 1'b1))) begin
            stream_out_24_TKEEP_int_regslice = grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_154_stream_out_24_TKEEP;
        end else if (((mode_read_reg_202 == 32'd2) & (grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_130_stream_out_24_TVALID == 1'b1))) begin
            stream_out_24_TKEEP_int_regslice = grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_130_stream_out_24_TKEEP;
        end else if (((grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_106_stream_out_24_TVALID == 1'b1) & (mode_read_reg_202 == 32'd3))) begin
            stream_out_24_TKEEP_int_regslice = grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_106_stream_out_24_TKEEP;
        end else if (((grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_82_stream_out_24_TVALID == 1'b1) & (mode_read_reg_202 == 32'd4))) begin
            stream_out_24_TKEEP_int_regslice = grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_82_stream_out_24_TKEEP;
        end else begin
            stream_out_24_TKEEP_int_regslice = 'bx;
        end
    end else begin
        stream_out_24_TKEEP_int_regslice = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if (((mode_read_reg_202 == 32'd0) & (grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_178_stream_out_24_TVALID == 1'b1))) begin
            stream_out_24_TLAST_int_regslice = grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_178_stream_out_24_TLAST;
        end else if (((mode_read_reg_202 == 32'd1) & (grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_154_stream_out_24_TVALID == 1'b1))) begin
            stream_out_24_TLAST_int_regslice = grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_154_stream_out_24_TLAST;
        end else if (((mode_read_reg_202 == 32'd2) & (grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_130_stream_out_24_TVALID == 1'b1))) begin
            stream_out_24_TLAST_int_regslice = grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_130_stream_out_24_TLAST;
        end else if (((grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_106_stream_out_24_TVALID == 1'b1) & (mode_read_reg_202 == 32'd3))) begin
            stream_out_24_TLAST_int_regslice = grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_106_stream_out_24_TLAST;
        end else if (((grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_82_stream_out_24_TVALID == 1'b1) & (mode_read_reg_202 == 32'd4))) begin
            stream_out_24_TLAST_int_regslice = grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_82_stream_out_24_TLAST;
        end else begin
            stream_out_24_TLAST_int_regslice = 'bx;
        end
    end else begin
        stream_out_24_TLAST_int_regslice = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if (((mode_read_reg_202 == 32'd0) & (grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_178_stream_out_24_TVALID == 1'b1))) begin
            stream_out_24_TSTRB_int_regslice = grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_178_stream_out_24_TSTRB;
        end else if (((mode_read_reg_202 == 32'd1) & (grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_154_stream_out_24_TVALID == 1'b1))) begin
            stream_out_24_TSTRB_int_regslice = grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_154_stream_out_24_TSTRB;
        end else if (((mode_read_reg_202 == 32'd2) & (grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_130_stream_out_24_TVALID == 1'b1))) begin
            stream_out_24_TSTRB_int_regslice = grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_130_stream_out_24_TSTRB;
        end else if (((grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_106_stream_out_24_TVALID == 1'b1) & (mode_read_reg_202 == 32'd3))) begin
            stream_out_24_TSTRB_int_regslice = grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_106_stream_out_24_TSTRB;
        end else if (((grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_82_stream_out_24_TVALID == 1'b1) & (mode_read_reg_202 == 32'd4))) begin
            stream_out_24_TSTRB_int_regslice = grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_82_stream_out_24_TSTRB;
        end else begin
            stream_out_24_TSTRB_int_regslice = 'bx;
        end
    end else begin
        stream_out_24_TSTRB_int_regslice = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if (((mode_read_reg_202 == 32'd0) & (grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_178_stream_out_24_TVALID == 1'b1))) begin
            stream_out_24_TUSER_int_regslice = grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_178_stream_out_24_TUSER;
        end else if (((mode_read_reg_202 == 32'd1) & (grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_154_stream_out_24_TVALID == 1'b1))) begin
            stream_out_24_TUSER_int_regslice = grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_154_stream_out_24_TUSER;
        end else if (((mode_read_reg_202 == 32'd2) & (grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_130_stream_out_24_TVALID == 1'b1))) begin
            stream_out_24_TUSER_int_regslice = grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_130_stream_out_24_TUSER;
        end else if (((grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_106_stream_out_24_TVALID == 1'b1) & (mode_read_reg_202 == 32'd3))) begin
            stream_out_24_TUSER_int_regslice = grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_106_stream_out_24_TUSER;
        end else if (((grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_82_stream_out_24_TVALID == 1'b1) & (mode_read_reg_202 == 32'd4))) begin
            stream_out_24_TUSER_int_regslice = grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_82_stream_out_24_TUSER;
        end else begin
            stream_out_24_TUSER_int_regslice = 'bx;
        end
    end else begin
        stream_out_24_TUSER_int_regslice = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((mode_read_reg_202 == 32'd0)) begin
            stream_out_24_TVALID_int_regslice = grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_178_stream_out_24_TVALID;
        end else if ((mode_read_reg_202 == 32'd1)) begin
            stream_out_24_TVALID_int_regslice = grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_154_stream_out_24_TVALID;
        end else if ((mode_read_reg_202 == 32'd2)) begin
            stream_out_24_TVALID_int_regslice = grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_130_stream_out_24_TVALID;
        end else if ((mode_read_reg_202 == 32'd3)) begin
            stream_out_24_TVALID_int_regslice = grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_106_stream_out_24_TVALID;
        end else if ((mode_read_reg_202 == 32'd4)) begin
            stream_out_24_TVALID_int_regslice = grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_82_stream_out_24_TVALID;
        end else begin
            stream_out_24_TVALID_int_regslice = 1'b0;
        end
    end else begin
        stream_out_24_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            if ((~(grp_read_fu_76_p2 == 32'd0) & ~(grp_read_fu_76_p2 == 32'd1) & ~(grp_read_fu_76_p2 == 32'd2) & ~(grp_read_fu_76_p2 == 32'd3) & ~(grp_read_fu_76_p2 == 32'd4) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b0 == ap_block_state3_on_subcall_done) & (1'b1 == ap_CS_fsm_state3) & ((mode_read_reg_202 == 32'd0) | ((mode_read_reg_202 == 32'd1) | ((mode_read_reg_202 == 32'd2) | ((mode_read_reg_202 == 32'd3) | (mode_read_reg_202 == 32'd4))))))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((regslice_both_stream_out_24_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state3_on_subcall_done = (((grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_106_ap_done == 1'b0) & (mode_read_reg_202 == 32'd3)) | ((grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_82_ap_done == 1'b0) & (mode_read_reg_202 == 32'd4)) | ((mode_read_reg_202 == 32'd0) & (grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_178_ap_done == 1'b0)) | ((mode_read_reg_202 == 32'd1) & (grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_154_ap_done == 1'b0)) | ((mode_read_reg_202 == 32'd2) & (grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_130_ap_done == 1'b0)));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_178_ap_start = grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_178_ap_start_reg;

assign grp_pixel_unpack_Pipeline_VITIS_LOOP_19_1_fu_178_stream_out_24_TREADY = (stream_out_24_TREADY_int_regslice & ap_CS_fsm_state3);

assign grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_154_ap_start = grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_154_ap_start_reg;

assign grp_pixel_unpack_Pipeline_VITIS_LOOP_40_4_fu_154_stream_out_24_TREADY = (stream_out_24_TREADY_int_regslice & ap_CS_fsm_state3);

assign grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_130_ap_start = grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_130_ap_start_reg;

assign grp_pixel_unpack_Pipeline_VITIS_LOOP_51_5_fu_130_stream_out_24_TREADY = (stream_out_24_TREADY_int_regslice & ap_CS_fsm_state3);

assign grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_106_ap_start = grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_106_ap_start_reg;

assign grp_pixel_unpack_Pipeline_VITIS_LOOP_68_7_fu_106_stream_out_24_TREADY = (stream_out_24_TREADY_int_regslice & ap_CS_fsm_state3);

assign grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_82_ap_start = grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_82_ap_start_reg;

assign grp_pixel_unpack_Pipeline_VITIS_LOOP_85_9_fu_82_stream_out_24_TREADY = (stream_out_24_TREADY_int_regslice & ap_CS_fsm_state3);

assign grp_read_fu_76_p2 = mode_0_data_reg;

assign stream_in_32_TREADY = regslice_both_stream_in_32_V_data_V_U_ack_in;

assign stream_out_24_TVALID = regslice_both_stream_out_24_V_data_V_U_vld_out;


reg find_kernel_block = 0;
// synthesis translate_off
`include "pixel_unpack_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //pixel_unpack

