#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2022.1 (64-bit)
#
# Filename    : base.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Thu Oct 26 16:53:27 EDT 2023
# SW Build 3526262 on Mon Apr 18 15:47:01 MDT 2022
#
# Tool Version Limit: 2022.04 
#
# usage: base.sh [-help]
# usage: base.sh [-lib_map_path]
# usage: base.sh [-noclean_files]
# usage: base.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'base.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Set vlogan compile options
vlogan_opts="-full64"

# Set vhdlan compile options
vhdlan_opts="-full64"

# Set vcs elaboration options
vcs_elab_opts="-full64 -debug_acc+pp+dmptf -t ps -licqueue -l elaborate.log"

# Set vcs simulation options
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xpm xil_defaultlib axi_lite_ipif_v3_0_4 lib_cdc_v1_0_2 interrupt_control_v3_1_4 axi_gpio_v2_0_28 xlconcat_v2_1_4 xlslice_v1_0_2 axi_infrastructure_v1_1_0 axi_vip_v1_1_12 processing_system7_vip_v1_0_14 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_26 fifo_generator_v13_2_7 axi_data_fifo_v2_1_25 axi_crossbar_v2_1_27 proc_sys_reset_v5_0_13 axi_intc_v4_1_17 lib_pkg_v1_0_2 lib_fifo_v1_0_16 blk_mem_gen_v8_4_5 lib_bmg_v1_0_14 lib_srl_fifo_v1_0_2 axi_datamover_v5_1_28 axi_vdma_v6_3_14 axis_infrastructure_v1_1_0 axis_register_slice_v1_1_26 v_vid_in_axi4s_v5_0_1 v_tc_v6_2_4 v_tc_v6_1_13 v_vid_in_axi4s_v4_0_9 v_axi4s_vid_out_v4_0_14 axi_protocol_converter_v2_1_26 axi_clock_converter_v2_1_25 axi_dwidth_converter_v2_1_26)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "base.sh - Script generated by export_simulation (Vivado v2022.1 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/4e49" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/fc4b/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8f5c/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/gabriel/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "/home/gabriel/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "/home/gabriel/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "/home/gabriel/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "/home/gabriel/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "/home/gabriel/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "/home/gabriel/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "/home/gabriel/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "/home/gabriel/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "/home/gabriel/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/4e49" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/fc4b/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8f5c/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/gabriel/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "/home/gabriel/Xilinx/Vivado/2022.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/home/gabriel/Xilinx/Vivado/2022.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "/home/gabriel/Xilinx/Vivado/2022.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/home/gabriel/Xilinx/Vivado/2022.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/f35b/src/family_support.vhd" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/f35b/src/common_types.vhd" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/f35b/src/pselect_f.vhd" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/f35b/src/address_decoder.vhd" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/f35b/src/slave_attachment.vhd" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/f35b/src/axi_lite_ipif.vhd" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/f35b/src/user_logic.vhd" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/f35b/src/iis_deser.vhd" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/f35b/src/iis_ser.vhd" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/f35b/src/i2s_ctrl.vhd" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_audio_codec_ctrl_0_0/sim/base_audio_codec_ctrl_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_28 $vhdlan_opts \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/3ed9/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_btns_gpio_0/sim/base_btns_gpio_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/4e49" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/fc4b/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8f5c/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/gabriel/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_clk_wiz_10MHz_0/base_clk_wiz_10MHz_0_clk_wiz.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_clk_wiz_10MHz_0/base_clk_wiz_10MHz_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconcat_v2_1_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/4e49" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/fc4b/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8f5c/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/gabriel/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/4b67/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/4e49" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/fc4b/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8f5c/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/gabriel/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_concat_interrupts_0/sim/base_concat_interrupts_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_leds_gpio_0/sim/base_leds_gpio_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlslice_v1_0_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/4e49" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/fc4b/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8f5c/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/gabriel/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/11d0/hdl/xlslice_v1_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/4e49" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/fc4b/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8f5c/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/gabriel/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_mb_iop_pmoda_reset_0/sim/base_mb_iop_pmoda_reset_0.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pmoda_rp_pin_sel_0/sim/base_pmoda_rp_pin_sel_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/4e49" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/fc4b/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8f5c/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/gabriel/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_12 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/4e49" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/fc4b/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8f5c/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/gabriel/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/1033/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_14 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/4e49" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/fc4b/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8f5c/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/gabriel/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/5765/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/4e49" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/fc4b/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8f5c/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/gabriel/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_ps7_0_0/sim/base_ps7_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/4e49" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/fc4b/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8f5c/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/gabriel/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_26 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/4e49" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/fc4b/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8f5c/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/gabriel/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/0a3f/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/4e49" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/fc4b/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8f5c/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/gabriel/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/83df/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_7 $vhdlan_opts \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/83df/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/4e49" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/fc4b/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8f5c/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/gabriel/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/83df/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_25 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/4e49" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/fc4b/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8f5c/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/gabriel/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/5390/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_27 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/4e49" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/fc4b/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8f5c/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/gabriel/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/3fa0/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/4e49" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/fc4b/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8f5c/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/gabriel/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_xbar_6/sim/base_xbar_6.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_rgbleds_gpio_0/sim/base_rgbleds_gpio_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_rst_ps7_0_fclk0_0/sim/base_rst_ps7_0_fclk0_0.vhd" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_rst_ps7_0_fclk1_0/sim/base_rst_ps7_0_fclk1_0.vhd" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_switches_gpio_0/sim/base_switches_gpio_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_intc_v4_1_17 $vhdlan_opts \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/802b/hdl/axi_intc_v4_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_system_interrupts_0/sim/base_system_interrupts_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/4e49" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/fc4b/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8f5c/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/gabriel/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_xbar_9/sim/base_xbar_9.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_xbar_10/sim/base_xbar_10.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_fifo_v1_0_16 $vhdlan_opts \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/6c82/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_4_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/4e49" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/fc4b/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8f5c/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/gabriel/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/25a8/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_bmg_v1_0_14 $vhdlan_opts \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/3a3e/hdl/lib_bmg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_28 $vhdlan_opts \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/1bb8/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_vdma_v6_3_14 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/4e49" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/fc4b/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8f5c/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/gabriel/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/fc4b/hdl/axi_vdma_v6_3_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_vdma_v6_3_14 $vhdlan_opts \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/fc4b/hdl/axi_vdma_v6_3_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_axi_vdma_0/sim/base_axi_vdma_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axis_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/4e49" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/fc4b/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8f5c/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/gabriel/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8713/hdl/axis_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_register_slice_v1_1_26 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/4e49" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/fc4b/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8f5c/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/gabriel/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/aca3/hdl/axis_register_slice_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/4e49" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/fc4b/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8f5c/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/gabriel/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_axis_register_slice_0_0/sim/base_axis_register_slice_0_0.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8f5c/hdl/verilog/color_convert_control_s_axi.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8f5c/hdl/verilog/color_convert_hls_deadlock_idx0_monitor.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8f5c/hdl/verilog/color_convert_mul_10s_8ns_18_1_1.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8f5c/hdl/verilog/color_convert_regslice_both.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8f5c/hdl/verilog/color_convert.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/sim/base_color_convert_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_axi_gpio_hdmiin_0/sim/base_axi_gpio_hdmiin_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/4e49" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/fc4b/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8f5c/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/gabriel/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/4b6f/color_swap.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_swap_0_0/sim/base_color_swap_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/269e/src/SyncBase.vhd" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/269e/src/EEPROM_8b.vhd" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/269e/src/TWI_SlaveCtl.vhd" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/269e/src/GlitchFilter.vhd" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/269e/src/SyncAsync.vhd" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/269e/src/DVI_Constants.vhd" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/269e/src/SyncAsyncReset.vhd" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/269e/src/PhaseAlign.vhd" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/269e/src/InputSERDES.vhd" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/269e/src/ChannelBond.vhd" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/269e/src/ResyncToBUFG.vhd" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/269e/src/TMDS_Decoder.vhd" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/269e/src/TMDS_Clocking.vhd" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/269e/src/dvi2rgb.vhd" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_dvi2rgb_0_0/sim/base_dvi2rgb_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work v_vid_in_axi4s_v5_0_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/4e49" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/fc4b/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8f5c/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/gabriel/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/b872/hdl/v_vid_in_axi4s_v5_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/4e49" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/fc4b/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8f5c/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/gabriel/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_v_vid_in_axi4s_0_0/sim/base_v_vid_in_axi4s_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work v_tc_v6_2_4 $vhdlan_opts \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/3e14/hdl/v_tc_v6_2_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_vtc_in_0/sim/base_vtc_in_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/4e49" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/fc4b/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8f5c/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/gabriel/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog/pixel_pack_control_s_axi.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog/pixel_pack_flow_control_loop_pipe_sequential_init.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog/pixel_pack_hls_deadlock_idx0_monitor.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog/pixel_pack_hls_deadlock_idx1_monitor.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog/pixel_pack_hls_deadlock_idx2_monitor.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog/pixel_pack_hls_deadlock_idx3_monitor.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog/pixel_pack_hls_deadlock_idx4_monitor.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog/pixel_pack_hls_deadlock_idx5_monitor.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog/pixel_pack_pixel_pack_Pipeline_VITIS_LOOP_21_1.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog/pixel_pack_pixel_pack_Pipeline_VITIS_LOOP_47_4.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog/pixel_pack_pixel_pack_Pipeline_VITIS_LOOP_62_5.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog/pixel_pack_pixel_pack_Pipeline_VITIS_LOOP_84_7.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog/pixel_pack_pixel_pack_Pipeline_VITIS_LOOP_101_9.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog/pixel_pack_regslice_both.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog/pixel_pack.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/sim/base_pixel_pack_0.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_axis_register_slice_0_1/sim/base_axis_register_slice_0_1.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/sim/base_color_convert_1.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/9097/src/mmcme2_drp.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/9097/src/axi_dynclk_S00_AXI.vhd" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/9097/src/axi_dynclk.vhd" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_axi_dynclk_0/sim/base_axi_dynclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/4e49" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/fc4b/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8f5c/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/gabriel/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_swap_0_1/sim/base_color_swap_0_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_hdmi_out_hpd_video_0/sim/base_hdmi_out_hpd_video_0.vhd" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/bd5a/src/ClockGen.vhd" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/bd5a/src/OutputSERDES.vhd" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/bd5a/src/TMDS_Encoder.vhd" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/bd5a/src/rgb2dvi.vhd" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_rgb2dvi_0_0/sim/base_rgb2dvi_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work v_tc_v6_1_13 $vhdlan_opts \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/b92e/hdl/v_tc_v6_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work v_vid_in_axi4s_v4_0_9 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/4e49" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/fc4b/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8f5c/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/gabriel/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/b2aa/hdl/v_vid_in_axi4s_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work v_axi4s_vid_out_v4_0_14 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/4e49" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/fc4b/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8f5c/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/gabriel/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/f733/hdl/v_axi4s_vid_out_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/4e49" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/fc4b/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8f5c/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/gabriel/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_v_axi4s_vid_out_0_0/sim/base_v_axi4s_vid_out_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_vtc_out_0/sim/base_vtc_out_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/4e49" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/fc4b/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8f5c/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/gabriel/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog/pixel_unpack_control_s_axi.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog/pixel_unpack_flow_control_loop_pipe_sequential_init.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog/pixel_unpack_hls_deadlock_idx0_monitor.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog/pixel_unpack_hls_deadlock_idx1_monitor.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog/pixel_unpack_hls_deadlock_idx2_monitor.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog/pixel_unpack_hls_deadlock_idx3_monitor.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog/pixel_unpack_hls_deadlock_idx4_monitor.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog/pixel_unpack_hls_deadlock_idx5_monitor.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog/pixel_unpack_pixel_unpack_Pipeline_VITIS_LOOP_19_1.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog/pixel_unpack_pixel_unpack_Pipeline_VITIS_LOOP_40_4.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog/pixel_unpack_pixel_unpack_Pipeline_VITIS_LOOP_51_5.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog/pixel_unpack_pixel_unpack_Pipeline_VITIS_LOOP_68_7.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog/pixel_unpack_pixel_unpack_Pipeline_VITIS_LOOP_85_9.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog/pixel_unpack_regslice_both.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog/pixel_unpack.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/sim/base_pixel_unpack_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_proc_sys_reset_pixelclk_0/sim/base_proc_sys_reset_pixelclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/4e49" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/fc4b/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8f5c/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/gabriel/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_xlconcat_0_0/sim/base_xlconcat_0_0.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_xlconcat_0_1/sim/base_xlconcat_0_1.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_s00_regslice_14/sim/base_s00_regslice_14.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_26 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/4e49" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/fc4b/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8f5c/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/gabriel/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/90c8/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/4e49" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/fc4b/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8f5c/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/gabriel/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_auto_pc_16/sim/base_auto_pc_16.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_25 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/4e49" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/fc4b/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8f5c/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/gabriel/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/e893/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/4e49" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/fc4b/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8f5c/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/gabriel/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_auto_cc_0/sim/base_auto_cc_0.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_auto_pc_17/sim/base_auto_pc_17.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_m00_regslice_14/sim/base_m00_regslice_14.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_auto_pc_10/sim/base_auto_pc_10.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_m01_regslice_14/sim/base_m01_regslice_14.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_m02_regslice_14/sim/base_m02_regslice_14.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_auto_pc_11/sim/base_auto_pc_11.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_m03_regslice_14/sim/base_m03_regslice_14.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_auto_pc_12/sim/base_auto_pc_12.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_m04_regslice_12/sim/base_m04_regslice_12.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_auto_pc_13/sim/base_auto_pc_13.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_m05_regslice_12/sim/base_m05_regslice_12.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_auto_pc_14/sim/base_auto_pc_14.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_m06_regslice_12/sim/base_m06_regslice_12.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_m07_regslice_12/sim/base_m07_regslice_12.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_auto_pc_15/sim/base_auto_pc_15.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_s00_regslice_15/sim/base_s00_regslice_15.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_auto_pc_18/sim/base_auto_pc_18.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_m00_regslice_15/sim/base_m00_regslice_15.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_m01_regslice_15/sim/base_m01_regslice_15.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_auto_cc_1/sim/base_auto_cc_1.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_m02_regslice_15/sim/base_m02_regslice_15.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_auto_cc_2/sim/base_auto_cc_2.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_m03_regslice_15/sim/base_m03_regslice_15.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_m04_regslice_13/sim/base_m04_regslice_13.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_m05_regslice_13/sim/base_m05_regslice_13.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_m06_regslice_13/sim/base_m06_regslice_13.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_auto_cc_3/sim/base_auto_cc_3.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_m07_regslice_13/sim/base_m07_regslice_13.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_auto_cc_4/sim/base_auto_cc_4.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_m08_regslice_5/sim/base_m08_regslice_5.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_m09_regslice_5/sim/base_m09_regslice_5.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_dwidth_converter_v2_1_26 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/4e49" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/fc4b/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8f5c/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/gabriel/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/b3c7/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/4e49" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/fc4b/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/8f5c/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/47a3/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ipshared/c1eb/hdl/verilog" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" +incdir+"$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" +incdir+"/home/gabriel/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_auto_us_1/sim/base_auto_us_1.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/ip/base_auto_pc_19/sim/base_auto_pc_19.v" \
    "$ref_dir/../../../../base.gen/sources_1/bd/base/sim/base.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log
}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.base xil_defaultlib.glbl -o base_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./base_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./base.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  else
    lib_map_path="/home/gabriel/Documents/Vivado/base/base.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key base_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc base_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./base.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: base.sh [-help]\n\
Usage: base.sh [-lib_map_path]\n\
Usage: base.sh [-reset_run]\n\
Usage: base.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
