# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/gabriel/Documents/Vivado/base/base.srcs/sources_1/bd/base/ip/base_btns_gpio_0/base_btns_gpio_0.xci
# IP: The module: 'base_btns_gpio_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/gabriel/Documents/Vivado/base/base.gen/sources_1/bd/base/ip/base_btns_gpio_0/base_btns_gpio_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_btns_gpio_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/gabriel/Documents/Vivado/base/base.gen/sources_1/bd/base/ip/base_btns_gpio_0/base_btns_gpio_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_btns_gpio_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/gabriel/Documents/Vivado/base/base.gen/sources_1/bd/base/ip/base_btns_gpio_0/base_btns_gpio_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_btns_gpio_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/gabriel/Documents/Vivado/base/base.srcs/sources_1/bd/base/ip/base_btns_gpio_0/base_btns_gpio_0.xci
# IP: The module: 'base_btns_gpio_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/gabriel/Documents/Vivado/base/base.gen/sources_1/bd/base/ip/base_btns_gpio_0/base_btns_gpio_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_btns_gpio_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/gabriel/Documents/Vivado/base/base.gen/sources_1/bd/base/ip/base_btns_gpio_0/base_btns_gpio_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_btns_gpio_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/gabriel/Documents/Vivado/base/base.gen/sources_1/bd/base/ip/base_btns_gpio_0/base_btns_gpio_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_btns_gpio_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
