// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module pixel_pack_pixel_pack_Pipeline_VITIS_LOOP_101_9 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        stream_in_24_TVALID,
        stream_out_32_TREADY,
        stream_in_24_TDATA,
        stream_in_24_TREADY,
        stream_in_24_TKEEP,
        stream_in_24_TSTRB,
        stream_in_24_TUSER,
        stream_in_24_TLAST,
        stream_out_32_TDATA,
        stream_out_32_TVALID,
        stream_out_32_TKEEP,
        stream_out_32_TSTRB,
        stream_out_32_TUSER,
        stream_out_32_TLAST
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   stream_in_24_TVALID;
input   stream_out_32_TREADY;
input  [23:0] stream_in_24_TDATA;
output   stream_in_24_TREADY;
input  [2:0] stream_in_24_TKEEP;
input  [2:0] stream_in_24_TSTRB;
input  [0:0] stream_in_24_TUSER;
input  [0:0] stream_in_24_TLAST;
output  [31:0] stream_out_32_TDATA;
output   stream_out_32_TVALID;
output  [3:0] stream_out_32_TKEEP;
output  [3:0] stream_out_32_TSTRB;
output  [0:0] stream_out_32_TUSER;
output  [0:0] stream_out_32_TLAST;

reg ap_idle;
reg stream_in_24_TREADY;
reg stream_out_32_TVALID;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    ap_CS_fsm_state2;
reg    ap_block_state2_pp0_stage1_iter0;
wire   [0:0] tmp_last_V_fu_134_p1;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    stream_in_24_TDATA_blk_n;
reg    stream_out_32_TDATA_blk_n;
reg   [0:0] empty_reg_208_3;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [7:0] grp_fu_103_p4;
reg   [7:0] tmp_3_reg_213;
wire   [7:0] grp_fu_113_p4;
reg   [7:0] tmp_5_reg_218;
wire   [7:0] trunc_ln674_fu_123_p1;
reg   [7:0] trunc_ln674_reg_223;
wire   [8:0] zext_ln232_1_fu_149_p1;
wire   [8:0] zext_ln232_fu_146_p1;
wire   [8:0] zext_ln232_3_fu_162_p1;
wire   [8:0] zext_ln232_2_fu_159_p1;
wire   [8:0] out_c1_V_fu_153_p2;
wire   [8:0] out_c2_V_fu_166_p2;
wire   [7:0] tmp_1_fu_186_p4;
wire   [7:0] trunc_ln674_5_fu_182_p1;
wire   [7:0] tmp_s_fu_172_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_start_int;
wire    ap_loop_init;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_done_reg = 1'b0;
end

pixel_pack_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((stream_out_32_TREADY == 1'b0) | (stream_in_24_TVALID == 1'b0)) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((stream_in_24_TVALID == 1'b0) | (ap_start_int == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        empty_reg_208_3 <= stream_in_24_TUSER;
        tmp_3_reg_213 <= {{stream_in_24_TDATA[15:8]}};
        tmp_5_reg_218 <= {{stream_in_24_TDATA[23:16]}};
        trunc_ln674_reg_223 <= trunc_ln674_fu_123_p1;
    end
end

always @ (*) begin
    if (((stream_in_24_TVALID == 1'b0) | (ap_start_int == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((stream_out_32_TREADY == 1'b0) | (stream_in_24_TVALID == 1'b0))) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((stream_out_32_TREADY == 1'b0) | (stream_in_24_TVALID == 1'b0)) & (tmp_last_V_fu_134_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if ((~((stream_out_32_TREADY == 1'b0) | (stream_in_24_TVALID == 1'b0)) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((stream_out_32_TREADY == 1'b0) | (stream_in_24_TVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1)))) begin
        stream_in_24_TDATA_blk_n = stream_in_24_TVALID;
    end else begin
        stream_in_24_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((~((stream_out_32_TREADY == 1'b0) | (stream_in_24_TVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state2)) | (~((stream_in_24_TVALID == 1'b0) | (ap_start_int == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        stream_in_24_TREADY = 1'b1;
    end else begin
        stream_in_24_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        stream_out_32_TDATA_blk_n = stream_out_32_TREADY;
    end else begin
        stream_out_32_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((stream_out_32_TREADY == 1'b0) | (stream_in_24_TVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
        stream_out_32_TVALID = 1'b1;
    end else begin
        stream_out_32_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((stream_in_24_TVALID == 1'b0) | (ap_start_int == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((~((stream_out_32_TREADY == 1'b0) | (stream_in_24_TVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((stream_in_24_TVALID == 1'b0) | (ap_start_int == 1'b0));
end

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0 = ((stream_out_32_TREADY == 1'b0) | (stream_in_24_TVALID == 1'b0));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign grp_fu_103_p4 = {{stream_in_24_TDATA[15:8]}};

assign grp_fu_113_p4 = {{stream_in_24_TDATA[23:16]}};

assign out_c1_V_fu_153_p2 = (zext_ln232_1_fu_149_p1 + zext_ln232_fu_146_p1);

assign out_c2_V_fu_166_p2 = (zext_ln232_3_fu_162_p1 + zext_ln232_2_fu_159_p1);

assign stream_out_32_TDATA = {{{{tmp_1_fu_186_p4}, {trunc_ln674_5_fu_182_p1}}, {tmp_s_fu_172_p4}}, {trunc_ln674_reg_223}};

assign stream_out_32_TKEEP = 4'd0;

assign stream_out_32_TLAST = stream_in_24_TLAST;

assign stream_out_32_TSTRB = 4'd0;

assign stream_out_32_TUSER = (stream_in_24_TUSER | empty_reg_208_3);

assign tmp_1_fu_186_p4 = {{out_c2_V_fu_166_p2[8:1]}};

assign tmp_last_V_fu_134_p1 = stream_in_24_TLAST;

assign tmp_s_fu_172_p4 = {{out_c1_V_fu_153_p2[8:1]}};

assign trunc_ln674_5_fu_182_p1 = stream_in_24_TDATA[7:0];

assign trunc_ln674_fu_123_p1 = stream_in_24_TDATA[7:0];

assign zext_ln232_1_fu_149_p1 = grp_fu_103_p4;

assign zext_ln232_2_fu_159_p1 = tmp_5_reg_218;

assign zext_ln232_3_fu_162_p1 = grp_fu_113_p4;

assign zext_ln232_fu_146_p1 = tmp_3_reg_213;

endmodule //pixel_pack_pixel_pack_Pipeline_VITIS_LOOP_101_9
