// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module pixel_pack_pixel_pack_Pipeline_VITIS_LOOP_62_5 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        stream_in_24_TVALID,
        stream_out_32_TREADY,
        stream_out_32_TDATA,
        stream_out_32_TVALID,
        stream_out_32_TKEEP,
        stream_out_32_TSTRB,
        stream_out_32_TUSER,
        stream_out_32_TLAST,
        stream_in_24_TDATA,
        stream_in_24_TREADY,
        stream_in_24_TKEEP,
        stream_in_24_TSTRB,
        stream_in_24_TUSER,
        stream_in_24_TLAST
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;
parameter    ap_const_lv32_0 = 32'd0;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   stream_in_24_TVALID;
input   stream_out_32_TREADY;
output  [31:0] stream_out_32_TDATA;
output   stream_out_32_TVALID;
output  [3:0] stream_out_32_TKEEP;
output  [3:0] stream_out_32_TSTRB;
output  [0:0] stream_out_32_TUSER;
output  [0:0] stream_out_32_TLAST;
input  [23:0] stream_in_24_TDATA;
output   stream_in_24_TREADY;
input  [2:0] stream_in_24_TKEEP;
input  [2:0] stream_in_24_TSTRB;
input  [0:0] stream_in_24_TUSER;
input  [0:0] stream_in_24_TLAST;

reg ap_idle;
reg stream_out_32_TVALID;
reg stream_in_24_TREADY;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [0:0] ap_phi_mux_delayed_last_phi_fu_106_p4;
reg   [0:0] ap_phi_mux_last_4_phi_fu_118_p4;
reg    ap_predicate_op24_read_state1;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_state4;
reg   [0:0] delayed_last_reg_103;
reg   [0:0] last_4_reg_114;
reg   [0:0] tmp_last_V_1_reg_292;
reg   [0:0] tmp_last_V_2_reg_308;
reg   [0:0] tmp_last_V_3_reg_329;
reg    ap_predicate_op47_read_state4;
reg    ap_predicate_op58_write_state4;
reg    ap_block_state4_pp0_stage3_iter0;
reg    ap_block_state4_io;
reg    stream_out_32_TDATA_blk_n;
reg    stream_in_24_TDATA_blk_n;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg   [0:0] tmp_user_V_3_reg_286;
wire   [0:0] grp_fu_190_p1;
wire   [7:0] trunc_ln674_fu_199_p1;
reg   [7:0] trunc_ln674_reg_296;
wire   [31:0] p_Result_s_fu_203_p5;
reg   [31:0] p_Result_s_reg_302;
reg    ap_predicate_op31_read_state2;
reg    ap_block_state2_pp0_stage1_iter0;
wire   [0:0] user_2_fu_218_p2;
reg   [0:0] user_2_reg_312;
wire   [7:0] trunc_ln674_1_fu_223_p1;
reg   [7:0] trunc_ln674_1_reg_318;
wire   [31:0] p_Result_1_fu_227_p5;
reg    ap_predicate_op39_read_state3;
reg    ap_block_state3_pp0_stage2_iter0;
wire   [0:0] user_3_fu_241_p2;
reg   [0:0] user_3_reg_333;
wire   [7:0] trunc_ln674_2_fu_246_p1;
reg   [7:0] trunc_ln674_2_reg_339;
wire   [31:0] p_Result_2_fu_250_p5;
wire    ap_loop_init;
reg   [0:0] ap_phi_mux_last_6_31073_phi_fu_177_p4;
reg   [31:0] ap_phi_mux_tmp_data_V_phi_fu_129_p8;
wire   [31:0] p_Result_3_fu_276_p5;
reg   [31:0] ap_phi_reg_pp0_iter0_tmp_data_V_reg_126;
reg   [0:0] ap_phi_mux_tmp_user_V_phi_fu_143_p8;
wire   [0:0] user_4_fu_266_p2;
reg   [0:0] ap_phi_reg_pp0_iter0_tmp_user_V_reg_140;
reg   [0:0] ap_phi_mux_tmp_last_V_phi_fu_158_p8;
wire   [7:0] trunc_ln674_3_fu_272_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_start_int;
reg    ap_condition_344;
reg    ap_condition_349;
reg    ap_condition_355;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_done_reg = 1'b0;
end

pixel_pack_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_start_int == 1'b0) | ((ap_predicate_op24_read_state1 == 1'b1) & (stream_in_24_TVALID == 1'b0))) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((last_4_reg_114 == 1'd0) & (delayed_last_reg_103 == 1'd0))) begin
        if ((1'b1 == ap_condition_355)) begin
            ap_phi_reg_pp0_iter0_tmp_data_V_reg_126 <= p_Result_2_fu_250_p5;
        end else if ((1'b1 == ap_condition_349)) begin
            ap_phi_reg_pp0_iter0_tmp_data_V_reg_126 <= p_Result_1_fu_227_p5;
        end else if ((1'b1 == ap_condition_344)) begin
            ap_phi_reg_pp0_iter0_tmp_data_V_reg_126 <= p_Result_s_fu_203_p5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((last_4_reg_114 == 1'd0) & (delayed_last_reg_103 == 1'd0))) begin
        if ((1'b1 == ap_condition_355)) begin
            ap_phi_reg_pp0_iter0_tmp_user_V_reg_140 <= user_3_fu_241_p2;
        end else if ((1'b1 == ap_condition_349)) begin
            ap_phi_reg_pp0_iter0_tmp_user_V_reg_140 <= user_2_reg_312;
        end else if ((1'b1 == ap_condition_344)) begin
            ap_phi_reg_pp0_iter0_tmp_user_V_reg_140 <= tmp_user_V_3_reg_286;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((ap_predicate_op24_read_state1 == 1'b1) & (stream_in_24_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        delayed_last_reg_103 <= 1'd0;
    end else if ((~((1'b1 == ap_block_state4_io) | ((ap_predicate_op58_write_state4 == 1'b1) & (stream_out_32_TREADY == 1'b0)) | ((ap_predicate_op47_read_state4 == 1'b1) & (stream_in_24_TVALID == 1'b0))) & (delayed_last_reg_103 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        delayed_last_reg_103 <= last_4_reg_114;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((ap_predicate_op24_read_state1 == 1'b1) & (stream_in_24_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        last_4_reg_114 <= 1'd0;
    end else if ((~((1'b1 == ap_block_state4_io) | ((ap_predicate_op58_write_state4 == 1'b1) & (stream_out_32_TREADY == 1'b0)) | ((ap_predicate_op47_read_state4 == 1'b1) & (stream_in_24_TVALID == 1'b0))) & (delayed_last_reg_103 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        last_4_reg_114 <= ap_phi_mux_last_6_31073_phi_fu_177_p4;
    end
end

always @ (posedge ap_clk) begin
    if ((~((stream_in_24_TVALID == 1'b0) & (ap_predicate_op31_read_state2 == 1'b1)) & (last_4_reg_114 == 1'd0) & (delayed_last_reg_103 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        p_Result_s_reg_302 <= p_Result_s_fu_203_p5;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((ap_predicate_op24_read_state1 == 1'b1) & (stream_in_24_TVALID == 1'b0))) & (ap_phi_mux_last_4_phi_fu_118_p4 == 1'd0) & (ap_phi_mux_delayed_last_phi_fu_106_p4 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        tmp_last_V_1_reg_292 <= stream_in_24_TLAST;
        tmp_user_V_3_reg_286 <= stream_in_24_TUSER;
        trunc_ln674_reg_296 <= trunc_ln674_fu_199_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((stream_in_24_TVALID == 1'b0) & (ap_predicate_op31_read_state2 == 1'b1)) & (tmp_last_V_1_reg_292 == 1'd0) & (last_4_reg_114 == 1'd0) & (delayed_last_reg_103 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp_last_V_2_reg_308 <= stream_in_24_TLAST;
        trunc_ln674_1_reg_318 <= trunc_ln674_1_fu_223_p1;
        user_2_reg_312 <= user_2_fu_218_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((stream_in_24_TVALID == 1'b0) & (ap_predicate_op39_read_state3 == 1'b1)) & (tmp_last_V_2_reg_308 == 1'd0) & (tmp_last_V_1_reg_292 == 1'd0) & (last_4_reg_114 == 1'd0) & (delayed_last_reg_103 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        tmp_last_V_3_reg_329 <= stream_in_24_TLAST;
        trunc_ln674_2_reg_339 <= trunc_ln674_2_fu_246_p1;
        user_3_reg_333 <= user_3_fu_241_p2;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) | ((ap_predicate_op24_read_state1 == 1'b1) & (stream_in_24_TVALID == 1'b0)))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((stream_in_24_TVALID == 1'b0) & (ap_predicate_op31_read_state2 == 1'b1))) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((stream_in_24_TVALID == 1'b0) & (ap_predicate_op39_read_state3 == 1'b1))) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state4_io) | ((ap_predicate_op58_write_state4 == 1'b1) & (stream_out_32_TREADY == 1'b0)) | ((ap_predicate_op47_read_state4 == 1'b1) & (stream_in_24_TVALID == 1'b0)))) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((ap_predicate_op24_read_state1 == 1'b1) & (stream_in_24_TVALID == 1'b0))) & (ap_phi_mux_delayed_last_phi_fu_106_p4 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((ap_predicate_op24_read_state1 == 1'b1) & (stream_in_24_TVALID == 1'b0))) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_phi_mux_delayed_last_phi_fu_106_p4 = 1'd0;
    end else begin
        ap_phi_mux_delayed_last_phi_fu_106_p4 = delayed_last_reg_103;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_phi_mux_last_4_phi_fu_118_p4 = 1'd0;
    end else begin
        ap_phi_mux_last_4_phi_fu_118_p4 = last_4_reg_114;
    end
end

always @ (*) begin
    if (((last_4_reg_114 == 1'd0) & (delayed_last_reg_103 == 1'd0))) begin
        ap_phi_mux_last_6_31073_phi_fu_177_p4 = ap_phi_mux_tmp_last_V_phi_fu_158_p8;
    end else begin
        ap_phi_mux_last_6_31073_phi_fu_177_p4 = 1'd1;
    end
end

always @ (*) begin
    if (((tmp_last_V_3_reg_329 == 1'd0) & (tmp_last_V_2_reg_308 == 1'd0) & (tmp_last_V_1_reg_292 == 1'd0) & (last_4_reg_114 == 1'd0) & (delayed_last_reg_103 == 1'd0))) begin
        ap_phi_mux_tmp_data_V_phi_fu_129_p8 = p_Result_3_fu_276_p5;
    end else begin
        ap_phi_mux_tmp_data_V_phi_fu_129_p8 = ap_phi_reg_pp0_iter0_tmp_data_V_reg_126;
    end
end

always @ (*) begin
    if (((tmp_last_V_3_reg_329 == 1'd0) & (tmp_last_V_2_reg_308 == 1'd0) & (tmp_last_V_1_reg_292 == 1'd0) & (last_4_reg_114 == 1'd0) & (delayed_last_reg_103 == 1'd0))) begin
        ap_phi_mux_tmp_last_V_phi_fu_158_p8 = stream_in_24_TLAST;
    end else begin
        ap_phi_mux_tmp_last_V_phi_fu_158_p8 = 1'd1;
    end
end

always @ (*) begin
    if (((tmp_last_V_3_reg_329 == 1'd0) & (tmp_last_V_2_reg_308 == 1'd0) & (tmp_last_V_1_reg_292 == 1'd0) & (last_4_reg_114 == 1'd0) & (delayed_last_reg_103 == 1'd0))) begin
        ap_phi_mux_tmp_user_V_phi_fu_143_p8 = user_4_fu_266_p2;
    end else begin
        ap_phi_mux_tmp_user_V_phi_fu_143_p8 = ap_phi_reg_pp0_iter0_tmp_user_V_reg_140;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state4_io) | ((ap_predicate_op58_write_state4 == 1'b1) & (stream_out_32_TREADY == 1'b0)) | ((ap_predicate_op47_read_state4 == 1'b1) & (stream_in_24_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_op47_read_state4 == 1'b1) & (1'b1 == ap_CS_fsm_state4)) | ((tmp_last_V_2_reg_308 == 1'd0) & (tmp_last_V_1_reg_292 == 1'd0) & (last_4_reg_114 == 1'd0) & (delayed_last_reg_103 == 1'd0) & (1'b1 == ap_CS_fsm_state3)) | ((tmp_last_V_1_reg_292 == 1'd0) & (last_4_reg_114 == 1'd0) & (delayed_last_reg_103 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((ap_predicate_op24_read_state1 == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        stream_in_24_TDATA_blk_n = stream_in_24_TVALID;
    end else begin
        stream_in_24_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_block_state4_io) | ((ap_predicate_op58_write_state4 == 1'b1) & (stream_out_32_TREADY == 1'b0)) | ((ap_predicate_op47_read_state4 == 1'b1) & (stream_in_24_TVALID == 1'b0))) & (ap_predicate_op47_read_state4 == 1'b1) & (1'b1 == ap_CS_fsm_state4)) | (~((ap_start_int == 1'b0) | ((ap_predicate_op24_read_state1 == 1'b1) & (stream_in_24_TVALID == 1'b0))) & (ap_predicate_op24_read_state1 == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | (~((stream_in_24_TVALID == 1'b0) & (ap_predicate_op39_read_state3 == 1'b1)) & (1'b1 == ap_CS_fsm_state3) & (ap_predicate_op39_read_state3 == 1'b1)) | (~((stream_in_24_TVALID == 1'b0) & (ap_predicate_op31_read_state2 == 1'b1)) & (1'b1 == ap_CS_fsm_state2) & (ap_predicate_op31_read_state2 == 1'b1)))) begin
        stream_in_24_TREADY = 1'b1;
    end else begin
        stream_in_24_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op58_write_state4 == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        stream_out_32_TDATA_blk_n = stream_out_32_TREADY;
    end else begin
        stream_out_32_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state4_io) | ((ap_predicate_op58_write_state4 == 1'b1) & (stream_out_32_TREADY == 1'b0)) | ((ap_predicate_op47_read_state4 == 1'b1) & (stream_in_24_TVALID == 1'b0))) & (ap_predicate_op58_write_state4 == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        stream_out_32_TVALID = 1'b1;
    end else begin
        stream_out_32_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start_int == 1'b0) | ((ap_predicate_op24_read_state1 == 1'b1) & (stream_in_24_TVALID == 1'b0))) & (ap_phi_mux_delayed_last_phi_fu_106_p4 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if ((~((ap_start_int == 1'b0) | ((ap_predicate_op24_read_state1 == 1'b1) & (stream_in_24_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((~((stream_in_24_TVALID == 1'b0) & (ap_predicate_op31_read_state2 == 1'b1)) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if ((~((stream_in_24_TVALID == 1'b0) & (ap_predicate_op39_read_state3 == 1'b1)) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if ((~((1'b1 == ap_block_state4_io) | ((ap_predicate_op58_write_state4 == 1'b1) & (stream_out_32_TREADY == 1'b0)) | ((ap_predicate_op47_read_state4 == 1'b1) & (stream_in_24_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | ((ap_predicate_op24_read_state1 == 1'b1) & (stream_in_24_TVALID == 1'b0)));
end

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0 = ((stream_in_24_TVALID == 1'b0) & (ap_predicate_op31_read_state2 == 1'b1));
end

always @ (*) begin
    ap_block_state3_pp0_stage2_iter0 = ((stream_in_24_TVALID == 1'b0) & (ap_predicate_op39_read_state3 == 1'b1));
end

always @ (*) begin
    ap_block_state4_io = ((ap_predicate_op58_write_state4 == 1'b1) & (stream_out_32_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state4_pp0_stage3_iter0 = (((ap_predicate_op58_write_state4 == 1'b1) & (stream_out_32_TREADY == 1'b0)) | ((ap_predicate_op47_read_state4 == 1'b1) & (stream_in_24_TVALID == 1'b0)));
end

always @ (*) begin
    ap_condition_344 = (~((stream_in_24_TVALID == 1'b0) & (ap_predicate_op31_read_state2 == 1'b1)) & (tmp_last_V_1_reg_292 == 1'd1) & (1'b1 == ap_CS_fsm_state2));
end

always @ (*) begin
    ap_condition_349 = (~((stream_in_24_TVALID == 1'b0) & (ap_predicate_op39_read_state3 == 1'b1)) & (tmp_last_V_2_reg_308 == 1'd1) & (tmp_last_V_1_reg_292 == 1'd0) & (1'b1 == ap_CS_fsm_state3));
end

always @ (*) begin
    ap_condition_355 = (~((stream_in_24_TVALID == 1'b0) & (ap_predicate_op39_read_state3 == 1'b1)) & (tmp_last_V_2_reg_308 == 1'd0) & (tmp_last_V_1_reg_292 == 1'd0) & (1'b1 == ap_CS_fsm_state3) & (grp_fu_190_p1 == 1'd1));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

always @ (*) begin
    ap_predicate_op24_read_state1 = ((ap_phi_mux_last_4_phi_fu_118_p4 == 1'd0) & (ap_phi_mux_delayed_last_phi_fu_106_p4 == 1'd0));
end

always @ (*) begin
    ap_predicate_op31_read_state2 = ((tmp_last_V_1_reg_292 == 1'd0) & (last_4_reg_114 == 1'd0) & (delayed_last_reg_103 == 1'd0));
end

always @ (*) begin
    ap_predicate_op39_read_state3 = ((tmp_last_V_2_reg_308 == 1'd0) & (tmp_last_V_1_reg_292 == 1'd0) & (last_4_reg_114 == 1'd0) & (delayed_last_reg_103 == 1'd0));
end

always @ (*) begin
    ap_predicate_op47_read_state4 = ((tmp_last_V_3_reg_329 == 1'd0) & (tmp_last_V_2_reg_308 == 1'd0) & (tmp_last_V_1_reg_292 == 1'd0) & (last_4_reg_114 == 1'd0) & (delayed_last_reg_103 == 1'd0));
end

always @ (*) begin
    ap_predicate_op58_write_state4 = ((last_4_reg_114 == 1'd0) & (delayed_last_reg_103 == 1'd0));
end

assign grp_fu_190_p1 = stream_in_24_TLAST;

assign p_Result_1_fu_227_p5 = {{p_Result_s_reg_302[31:16]}, {trunc_ln674_1_reg_318}, {p_Result_s_reg_302[7:0]}};

assign p_Result_2_fu_250_p5 = {{p_Result_1_fu_227_p5[31:24]}, {trunc_ln674_2_fu_246_p1}, {p_Result_1_fu_227_p5[15:0]}};

assign p_Result_3_fu_276_p5 = {{{{trunc_ln674_3_fu_272_p1}, {trunc_ln674_2_reg_339}}, {trunc_ln674_1_reg_318}}, {trunc_ln674_reg_296}};

assign p_Result_s_fu_203_p5 = {{ap_const_lv32_0[31:8]}, {trunc_ln674_reg_296}};

assign stream_out_32_TDATA = ap_phi_mux_tmp_data_V_phi_fu_129_p8;

assign stream_out_32_TKEEP = 4'd0;

assign stream_out_32_TLAST = ap_phi_mux_tmp_last_V_phi_fu_158_p8;

assign stream_out_32_TSTRB = 4'd0;

assign stream_out_32_TUSER = ap_phi_mux_tmp_user_V_phi_fu_143_p8;

assign trunc_ln674_1_fu_223_p1 = stream_in_24_TDATA[7:0];

assign trunc_ln674_2_fu_246_p1 = stream_in_24_TDATA[7:0];

assign trunc_ln674_3_fu_272_p1 = stream_in_24_TDATA[7:0];

assign trunc_ln674_fu_199_p1 = stream_in_24_TDATA[7:0];

assign user_2_fu_218_p2 = (tmp_user_V_3_reg_286 | stream_in_24_TUSER);

assign user_3_fu_241_p2 = (user_2_reg_312 | stream_in_24_TUSER);

assign user_4_fu_266_p2 = (user_3_reg_333 | stream_in_24_TUSER);

endmodule //pixel_pack_pixel_pack_Pipeline_VITIS_LOOP_62_5
