# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/base.xdc

# Block Designs: bd/base/base.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base || ORIG_REF_NAME==base} -quiet] -quiet

# IP: bd/base/ip/base_audio_codec_ctrl_0_0/base_audio_codec_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_audio_codec_ctrl_0_0 || ORIG_REF_NAME==base_audio_codec_ctrl_0_0} -quiet] -quiet

# IP: bd/base/ip/base_concat_interrupts_0/base_concat_interrupts_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_concat_interrupts_0 || ORIG_REF_NAME==base_concat_interrupts_0} -quiet] -quiet

# IP: bd/base/ip/base_xbar_6/base_xbar_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_xbar_6 || ORIG_REF_NAME==base_xbar_6} -quiet] -quiet

# IP: bd/base/ip/base_ps7_0_axi_periph_0/base_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_ps7_0_axi_periph_0 || ORIG_REF_NAME==base_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/base/ip/base_system_interrupts_0/base_system_interrupts_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_system_interrupts_0 || ORIG_REF_NAME==base_system_interrupts_0} -quiet] -quiet

# IP: bd/base/ip/base_xbar_9/base_xbar_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_xbar_9 || ORIG_REF_NAME==base_xbar_9} -quiet] -quiet

# IP: bd/base/ip/base_axi_interconnect_0_1/base_axi_interconnect_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_axi_interconnect_0_1 || ORIG_REF_NAME==base_axi_interconnect_0_1} -quiet] -quiet

# IP: bd/base/ip/base_axi_vdma_0/base_axi_vdma_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_axi_vdma_0 || ORIG_REF_NAME==base_axi_vdma_0} -quiet] -quiet

# IP: bd/base/ip/base_axis_register_slice_0_0/base_axis_register_slice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_axis_register_slice_0_0 || ORIG_REF_NAME==base_axis_register_slice_0_0} -quiet] -quiet

# IP: bd/base/ip/base_color_convert_0/base_color_convert_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_color_convert_0 || ORIG_REF_NAME==base_color_convert_0} -quiet] -quiet

# IP: bd/base/ip/base_color_swap_0_0/base_color_swap_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_color_swap_0_0 || ORIG_REF_NAME==base_color_swap_0_0} -quiet] -quiet

# IP: bd/base/ip/base_v_vid_in_axi4s_0_0/base_v_vid_in_axi4s_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==base_v_vid_in_axi4s_0_0} -quiet] -quiet

# IP: bd/base/ip/base_vtc_in_0/base_vtc_in_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_vtc_in_0 || ORIG_REF_NAME==base_vtc_in_0} -quiet] -quiet

# IP: bd/base/ip/base_axi_gpio_hdmiin_0/base_axi_gpio_hdmiin_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_axi_gpio_hdmiin_0 || ORIG_REF_NAME==base_axi_gpio_hdmiin_0} -quiet] -quiet

# IP: bd/base/ip/base_dvi2rgb_0_0/base_dvi2rgb_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_dvi2rgb_0_0 || ORIG_REF_NAME==base_dvi2rgb_0_0} -quiet] -quiet

# IP: bd/base/ip/base_pixel_pack_0/base_pixel_pack_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_pixel_pack_0 || ORIG_REF_NAME==base_pixel_pack_0} -quiet] -quiet

# IP: bd/base/ip/base_axis_register_slice_0_1/base_axis_register_slice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_axis_register_slice_0_1 || ORIG_REF_NAME==base_axis_register_slice_0_1} -quiet] -quiet

# IP: bd/base/ip/base_color_convert_1/base_color_convert_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_color_convert_1 || ORIG_REF_NAME==base_color_convert_1} -quiet] -quiet

# IP: bd/base/ip/base_axi_dynclk_0/base_axi_dynclk_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_axi_dynclk_0 || ORIG_REF_NAME==base_axi_dynclk_0} -quiet] -quiet

# IP: bd/base/ip/base_color_swap_0_1/base_color_swap_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_color_swap_0_1 || ORIG_REF_NAME==base_color_swap_0_1} -quiet] -quiet

# IP: bd/base/ip/base_v_axi4s_vid_out_0_0/base_v_axi4s_vid_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==base_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/base/ip/base_vtc_out_0/base_vtc_out_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_vtc_out_0 || ORIG_REF_NAME==base_vtc_out_0} -quiet] -quiet

# IP: bd/base/ip/base_hdmi_out_hpd_video_0/base_hdmi_out_hpd_video_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_hdmi_out_hpd_video_0 || ORIG_REF_NAME==base_hdmi_out_hpd_video_0} -quiet] -quiet

# IP: bd/base/ip/base_rgb2dvi_0_0/base_rgb2dvi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_rgb2dvi_0_0 || ORIG_REF_NAME==base_rgb2dvi_0_0} -quiet] -quiet

# IP: bd/base/ip/base_pixel_unpack_0/base_pixel_unpack_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_pixel_unpack_0 || ORIG_REF_NAME==base_pixel_unpack_0} -quiet] -quiet

# IP: bd/base/ip/base_xlconcat_0_0/base_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_xlconcat_0_0 || ORIG_REF_NAME==base_xlconcat_0_0} -quiet] -quiet

# IP: bd/base/ip/base_proc_sys_reset_pixelclk_0/base_proc_sys_reset_pixelclk_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_proc_sys_reset_pixelclk_0 || ORIG_REF_NAME==base_proc_sys_reset_pixelclk_0} -quiet] -quiet

# IP: bd/base/ip/base_xbar_10/base_xbar_10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_xbar_10 || ORIG_REF_NAME==base_xbar_10} -quiet] -quiet

# IP: bd/base/ip/base_axi_mem_intercon_1/base_axi_mem_intercon_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_axi_mem_intercon_1 || ORIG_REF_NAME==base_axi_mem_intercon_1} -quiet] -quiet

# IP: bd/base/ip/base_xlconcat_0_1/base_xlconcat_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_xlconcat_0_1 || ORIG_REF_NAME==base_xlconcat_0_1} -quiet] -quiet

# IP: bd/base/ip/base_btns_gpio_0/base_btns_gpio_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_btns_gpio_0 || ORIG_REF_NAME==base_btns_gpio_0} -quiet] -quiet

# IP: bd/base/ip/base_leds_gpio_0/base_leds_gpio_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_leds_gpio_0 || ORIG_REF_NAME==base_leds_gpio_0} -quiet] -quiet

# IP: bd/base/ip/base_ps7_0_0/base_ps7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_ps7_0_0 || ORIG_REF_NAME==base_ps7_0_0} -quiet] -quiet

# IP: bd/base/ip/base_rgbleds_gpio_0/base_rgbleds_gpio_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_rgbleds_gpio_0 || ORIG_REF_NAME==base_rgbleds_gpio_0} -quiet] -quiet

# IP: bd/base/ip/base_rst_ps7_0_fclk0_0/base_rst_ps7_0_fclk0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_rst_ps7_0_fclk0_0 || ORIG_REF_NAME==base_rst_ps7_0_fclk0_0} -quiet] -quiet

# IP: bd/base/ip/base_rst_ps7_0_fclk1_0/base_rst_ps7_0_fclk1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_rst_ps7_0_fclk1_0 || ORIG_REF_NAME==base_rst_ps7_0_fclk1_0} -quiet] -quiet

# IP: bd/base/ip/base_switches_gpio_0/base_switches_gpio_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_switches_gpio_0 || ORIG_REF_NAME==base_switches_gpio_0} -quiet] -quiet

# IP: bd/base/ip/base_s00_regslice_8/base_s00_regslice_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_s00_regslice_8 || ORIG_REF_NAME==base_s00_regslice_8} -quiet] -quiet

# IP: bd/base/ip/base_auto_pc_6/base_auto_pc_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_auto_pc_6 || ORIG_REF_NAME==base_auto_pc_6} -quiet] -quiet

# IP: bd/base/ip/base_m00_regslice_8/base_m00_regslice_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_m00_regslice_8 || ORIG_REF_NAME==base_m00_regslice_8} -quiet] -quiet

# IP: bd/base/ip/base_auto_pc_0/base_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_auto_pc_0 || ORIG_REF_NAME==base_auto_pc_0} -quiet] -quiet

# IP: bd/base/ip/base_m01_regslice_8/base_m01_regslice_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_m01_regslice_8 || ORIG_REF_NAME==base_m01_regslice_8} -quiet] -quiet

# IP: bd/base/ip/base_m02_regslice_8/base_m02_regslice_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_m02_regslice_8 || ORIG_REF_NAME==base_m02_regslice_8} -quiet] -quiet

# IP: bd/base/ip/base_auto_pc_1/base_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_auto_pc_1 || ORIG_REF_NAME==base_auto_pc_1} -quiet] -quiet

# IP: bd/base/ip/base_m03_regslice_8/base_m03_regslice_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_m03_regslice_8 || ORIG_REF_NAME==base_m03_regslice_8} -quiet] -quiet

# IP: bd/base/ip/base_auto_pc_2/base_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_auto_pc_2 || ORIG_REF_NAME==base_auto_pc_2} -quiet] -quiet

# IP: bd/base/ip/base_m04_regslice_8/base_m04_regslice_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_m04_regslice_8 || ORIG_REF_NAME==base_m04_regslice_8} -quiet] -quiet

# IP: bd/base/ip/base_auto_pc_3/base_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_auto_pc_3 || ORIG_REF_NAME==base_auto_pc_3} -quiet] -quiet

# IP: bd/base/ip/base_m05_regslice_8/base_m05_regslice_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_m05_regslice_8 || ORIG_REF_NAME==base_m05_regslice_8} -quiet] -quiet

# IP: bd/base/ip/base_auto_pc_4/base_auto_pc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_auto_pc_4 || ORIG_REF_NAME==base_auto_pc_4} -quiet] -quiet

# IP: bd/base/ip/base_m06_regslice_8/base_m06_regslice_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_m06_regslice_8 || ORIG_REF_NAME==base_m06_regslice_8} -quiet] -quiet

# IP: bd/base/ip/base_auto_pc_5/base_auto_pc_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_auto_pc_5 || ORIG_REF_NAME==base_auto_pc_5} -quiet] -quiet

# IP: bd/base/ip/base_s00_regslice_9/base_s00_regslice_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_s00_regslice_9 || ORIG_REF_NAME==base_s00_regslice_9} -quiet] -quiet

# IP: bd/base/ip/base_auto_pc_7/base_auto_pc_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_auto_pc_7 || ORIG_REF_NAME==base_auto_pc_7} -quiet] -quiet

# IP: bd/base/ip/base_m00_regslice_9/base_m00_regslice_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_m00_regslice_9 || ORIG_REF_NAME==base_m00_regslice_9} -quiet] -quiet

# IP: bd/base/ip/base_m01_regslice_9/base_m01_regslice_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_m01_regslice_9 || ORIG_REF_NAME==base_m01_regslice_9} -quiet] -quiet

# IP: bd/base/ip/base_auto_cc_0/base_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_auto_cc_0 || ORIG_REF_NAME==base_auto_cc_0} -quiet] -quiet

# IP: bd/base/ip/base_m02_regslice_9/base_m02_regslice_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_m02_regslice_9 || ORIG_REF_NAME==base_m02_regslice_9} -quiet] -quiet

# IP: bd/base/ip/base_auto_cc_1/base_auto_cc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_auto_cc_1 || ORIG_REF_NAME==base_auto_cc_1} -quiet] -quiet

# IP: bd/base/ip/base_m03_regslice_9/base_m03_regslice_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_m03_regslice_9 || ORIG_REF_NAME==base_m03_regslice_9} -quiet] -quiet

# IP: bd/base/ip/base_m04_regslice_9/base_m04_regslice_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_m04_regslice_9 || ORIG_REF_NAME==base_m04_regslice_9} -quiet] -quiet

# IP: bd/base/ip/base_m05_regslice_9/base_m05_regslice_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_m05_regslice_9 || ORIG_REF_NAME==base_m05_regslice_9} -quiet] -quiet

# IP: bd/base/ip/base_m06_regslice_9/base_m06_regslice_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_m06_regslice_9 || ORIG_REF_NAME==base_m06_regslice_9} -quiet] -quiet

# IP: bd/base/ip/base_auto_cc_2/base_auto_cc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_auto_cc_2 || ORIG_REF_NAME==base_auto_cc_2} -quiet] -quiet

# IP: bd/base/ip/base_m07_regslice_0/base_m07_regslice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_m07_regslice_0 || ORIG_REF_NAME==base_m07_regslice_0} -quiet] -quiet

# IP: bd/base/ip/base_auto_cc_3/base_auto_cc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_auto_cc_3 || ORIG_REF_NAME==base_auto_cc_3} -quiet] -quiet

# IP: bd/base/ip/base_m08_regslice_0/base_m08_regslice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_m08_regslice_0 || ORIG_REF_NAME==base_m08_regslice_0} -quiet] -quiet

# IP: bd/base/ip/base_m09_regslice_0/base_m09_regslice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_m09_regslice_0 || ORIG_REF_NAME==base_m09_regslice_0} -quiet] -quiet

# IP: bd/base/ip/base_auto_us_0/base_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_auto_us_0 || ORIG_REF_NAME==base_auto_us_0} -quiet] -quiet

# IP: bd/base/ip/base_auto_pc_8/base_auto_pc_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_auto_pc_8 || ORIG_REF_NAME==base_auto_pc_8} -quiet] -quiet

# XDC: /home/gabriel/Documents/Vivado/base/base.gen/sources_1/bd/base/base_ooc.xdc
